version: '3.4'

networks:
    sgh-network:
        driver: bridge 

services:
  sgh.api:
    image: ${DOCKER_REGISTRY-}sgh
    build:
      context: .
      dockerfile: SGH/Dockerfile
    env_file: .env
    ports:
        - "5000:5000"
        - "443:443"
    networks:
        - sgh-network

  sgh.database:
    image: postgres
    container_name: SGH.Database
    env_file: .env
    volumes:
     - ./postgres/data:/data/postgresss     
    ports:
        - "5432:5432"
    networks:
        - sgh-network   