version: '3.4'

networks:
    sgh-network:
        driver: bridge 

services:
  sgh.api:
    image: ${DOCKER_REGISTRY-}sgh
    container_name: SGH.Api
    build:
      context: .
      dockerfile: SGH/Dockerfile
    ports:
        - "5000:5000"
        - "443:443"
    networks:
        - sgh-network

  sgh.database:
    image: postgres
    container_name: SGH.Database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sghDb347#"
      PGDATA: /data/postgres
    volumes:
     - ./postgres/data:/data/postgresss     
    ports:
        - "5432:5432"
    networks:
        - sgh-network   