on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['2.0', '2.1.x', 2.2.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore SGH.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore SGH.sln
      - name: Test
        run: dotnet test --verbosity minimal --collect:"XPlat Code Coverage" SGH.sln